import numbers

import numpy as np
import scipy.linalg

from pygto import lib
from pygto.basis import BasisSpec, ContractedBasis, ContractedChannel


lnames = 'spdfghikl'
LMAX = len(lnames)-1


class ANO(lib.StreamObject):
    ''' Contract primitive basis functions by Atomic Natural Orbital (ANO) coefficients.

        Input:
            spec (BasisSpec):
                BasisSpec object providing the uncontracted primitive set. One angular
                momentum must have only one channel. If multiple channels correspond to
                one angular momentum, call `spec.merge_angular_momentum()` first.
            ano_input_func (callable):
                The functional signature is:
                    ano_input_func(spec) -> dm, ovlp
                where `dm` is a density matrix in the AO basis, and `ovlp` is the AO
                overlap matrix. Both matrices must be of size `(spec.nao, spec.nao)`.
                For PySCF users, use `:func:lib.pyscf_helper.get_ano_input_func` to
                generate this function.

        Args:
            nocc_thr (float):
                Threshold for ANO selection by ANO occupation number. Default is 0.1.
            pct_occ (float):
                Accumulated percentage occuation for ANO selection. Default is None.
                If provided, `nocc_thr` is ignored.
            nkeep_by_l (dict):
                Number of ANOs to keep in each l-channel. Default is None. If provided,
                both `nocc_thr` and `pct_occ` are ignored.
                Example: `{0: 2, 1: 1}` will keep 2 s-type ANOs and 1-p-type ANO,
                selected by ANO occupation number.
            nfree_by_l (dict):
                Number of primitives to decontract for each l-channel. Default is None.
                If both `nkeep_by_l` and `ctr_by_l` are None, decontraction is not performed.
                Example: `{0: 2, 1: 1}` will decontract the most diffuse two primitives
                in the s-channel and the most diffuse primitive from the p-channel.
            ctr_by_l (dict):
                Directly specify contraction pattern for each l-channel. Default is None.
                If both `nkeep_by_l` and `ctr_by_l` are None, decontraction is not performed.
                Example: `{0: [[0],[1],[2,3,4,5,6,7,8]], 1:[[0],[1,2,3]]}` will keep the
                ANO contraction for primitive 2--8 while decontract primitive 0 and 1 in
                the s-channel, and keep the ANO contraction for the primitive 1--3 while
                decontracting primitive 0 in the p-channel.

        Attributes generated by `kernel`:
            basis (ContractedBasis):
                Final decontracted ANO basis.
            ctr_basis (ContractedBasis):
                The fully contracted ANO basis.

            Note: If both `nkeep_by_l` and `ctr_by_l` are None (which is the default),
            `basis` is a copy of `ctr_basis` because no decontraction is performed.
    '''

    def __init__(self, spec, ano_input_func, atm=None, verbose=None):
        self._spec = None
        self.spec = spec
        self.ano_input_func = ano_input_func
        self.atm = atm
        if verbose is not None: self.verbose = verbose

        # attributes with default
        self.nocc_thr = 0.1
        self.pct_occ = None
        self.nkeep_by_l = None
        self.nfree_by_l = None
        self.ctr_by_l = None

        # attributes generated by kernel; do not modify
        self.ctr_basis = None
        self.basis = None

    @property
    def spec(self):
        return self._spec

    @spec.setter
    def spec(self, spec):
        if not isinstance(spec, BasisSpec):
            raise TypeError('spec must be BasisSpec object.')
        if len(set(spec.angular_momenta)) != len(spec.angular_momenta):
            raise ValueError('Multiple channels in spec have the same l. '
                             'Call `spec.merge_angular_momentum` first.')

        self._spec = spec

    def get_ao_l(self, spec):
        ''' Return a list indicating the angular momentum of each AO.
        '''
        ao_l = np.zeros(spec.nao, dtype=int)
        i1 = 0
        for c in spec.channels:
            i0, i1 = i1, i1+c.nao
            ao_l[i0:i1] = c.l
        return ao_l

    def full_contraction(self, spec, dm, s, nocc_thr=None, pct_occ=None, nkeep_by_l=None):
        ''' Return a fully contracted basis by ANO coefficients.
        '''
        if nocc_thr is None: nocc_thr = self.nocc_thr
        if pct_occ is None: pct_occ = self.pct_occ
        if nkeep_by_l is None: nkeep_by_l = self.nkeep_by_l

        ao_l = self.get_ao_l(spec)
        dm_by_l = spherical_average_by_l(dm, ao_l)
        s_by_l = spherical_average_by_l(s, ao_l)

        channels = []
        for l in range(LMAX+1):
            if not l in dm_by_l: continue
            occ_l, coeff_l = eigh_dm(dm_by_l[l], s_by_l[l])
            nkeep = None if nkeep_by_l is None else nkeep_by_l[l]
            nkeep = select_natural_orbitals(occ_l, nocc_thr, pct_occ, nkeep)
            if nkeep == 0:
                continue
            occ = occ_l[:nkeep]
            coeff = coeff_l[:,:nkeep]
            occ, coeff = sort_ano(occ, coeff)
            e = np.sort(spec.exponents_by_l(l))[::-1]
            channels.append( ContractedChannel(l, e, coeff) )
        basis = ContractedBasis(channels).set(atm=self.atm)

        return basis

    def decontraction(self, ctr_basis, nfree_by_l=None, ctr_by_l=None):
        ''' Partially decontract a fully contracted basis.
        '''
        if ctr_by_l is None: ctr_by_l = self.ctr_by_l
        if ctr_by_l is None: ctr_by_l = self._get_ctr_pattern(nfree_by_l)

        channels = []
        for c in ctr_basis.channels:
            l = c.l
            coeff = c.coefficients.copy()
            e = c.exponents.copy()
            try:
                ctr = ctr_by_l[l]
            except (KeyError, IndexError, TypeError):
                raise ValueError('Missing contraction pattern for l=%d.' % l)

            checked_ctr = []
            primitive_idx = []
            for idx in ctr:
                try:
                    idx = list(idx)
                except TypeError:
                    raise TypeError('Each contraction group must contain integer indices.')
                if len(idx) == 0:
                    raise ValueError('Contraction groups cannot be empty.')
                if not all(isinstance(i, numbers.Integral) and not isinstance(i, bool)
                           for i in idx):
                    raise TypeError('Each contraction group must contain integer indices.')
                checked_ctr.append(idx)
                primitive_idx.extend(idx)
            if (len(primitive_idx) != c.nprim or
                    set(primitive_idx) != set(range(c.nprim))):
                raise ValueError('Contraction pattern for l=%d must contain each primitive '
                                 'index exactly once.' % l)

            ctr = checked_ctr
            for idx in ctr:
                channel = ContractedChannel(l, e[idx], coeff[idx])
                if channel.nctr >= channel.nprim:
                    channel.coefficients = np.eye(channel.nprim)
                channels.append( channel )
        basis = ContractedBasis(channels).set(atm=self.atm)
        return basis

    def _get_ctr_pattern(self, nfree_by_l=None):
        if nfree_by_l is None: nfree_by_l = self.nfree_by_l
        if nfree_by_l is None:
            raise ValueError('Must provide nfree_by_l or ctr_pattern.')

        ctr_by_l = {}
        for c in self.spec.channels:
            l = c.l
            nprim = c.nbas
            nfree = nfree_by_l[l]
            if nfree > nprim:
                raise ValueError('nfree for l %d exceeds nprim (%d > %d)' % (
                    l, nfree, nprim))
            ctr_by_l[l] = [[i] for i in range(nfree)]
            if nfree < nprim:
                ctr_by_l[l] += [list(range(nfree,nprim))]
        return ctr_by_l

    def kernel(self, **kwargs):
        self.set(**kwargs)

        spec = self.spec.copy()

        dm, s = self.ano_input_func(spec)
        self.ctr_basis = self.full_contraction(spec, dm, s)
        if self.nfree_by_l is None and self.ctr_by_l is None:
            self.basis = self.ctr_basis.copy()
        else:
            self.basis = self.decontraction(self.ctr_basis, self.nfree_by_l, self.ctr_by_l)

        return self.basis


def spherical_average_by_l(matrix, ao_l):
    ao_l = np.asarray(ao_l)
    if ao_l.ndim != 1: raise ValueError('ao_l must be a 1-D array.')

    matrix_by_l = {}
    for l in range(LMAX+1):
        idx = np.where(ao_l == l)[0]
        if idx.size == 0:
            continue
        degen = 2*l + 1
        nao_l = idx.size
        if nao_l % degen != 0:
            raise ValueError('Only spherical GTOs are supported!')
        nbas_l = nao_l // degen
        matrix_l = matrix[idx[:,None], idx].reshape(nbas_l,degen,nbas_l,degen)
        matrix_l = np.einsum('ixjx->ij', matrix_l) / degen
        matrix_by_l[l] = matrix_l
    return matrix_by_l


def eigh_dm(d, s):
    sds = np.linalg.multi_dot((s,d,s))
    e, c = scipy.linalg.eigh(sds, s)
    e = e[::-1]
    c = c[:,::-1]
    return e, c


def select_natural_orbitals(occ, nocc_thr=0.1, pct_occ=None, nkeep=None):
    if not np.allclose(occ, np.sort(occ)[::-1]):
        raise ValueError('occ must be sorted descendingly.')

    if nkeep is not None:
        if not isinstance(nkeep, numbers.Integral) or isinstance(nkeep, bool):
            raise TypeError('nkeep must be an integer.')
        if nkeep < 0 or nkeep > len(occ):
            raise ValueError('nkeep must satisfy 0 <= nkeep <= len(occ).')
        nmo_keep = nkeep
    elif pct_occ is not None:
        if (not isinstance(pct_occ, numbers.Real) or isinstance(pct_occ, bool) or
                not np.isfinite(pct_occ)):
            raise TypeError('pct_occ must be a finite real number.')
        if pct_occ <= 0. or pct_occ > 1.:
            raise ValueError('pct_occ must satisfy 0 < pct_occ <= 1.')
        cumsum = np.cumsum(occ/np.sum(occ))
        if np.any(cumsum >= pct_occ):
            nmo_keep = np.where([c >= pct_occ for c in cumsum])[0][0] + 1
        else:
            nmo_keep = cumsum.size
    else:
        if (not isinstance(nocc_thr, numbers.Real) or isinstance(nocc_thr, bool) or
                not np.isfinite(nocc_thr)):
            raise TypeError('nocc_thr must be a finite real number.')
        nmo_keep = np.count_nonzero(occ > nocc_thr)

    return nmo_keep


def sort_ano(occ, coeff, tol=1e-2):
    ''' occ is a 1D array of size (nctr, )
        coeff is a 2D array of size (nprim, nctr), where nctr <= nprim

        Sort columns of coeff as follows:
            1. by occ value in descending order
            2. in case of degenerate occ values, sort ascendingly by abs(coeff[-1,deg_idx])
        Degenerate occ values are determined from descendingly sorted occ by:
            mask = occ[:-1] - occ[1:] < tol
    '''
    occ = np.asarray(occ, dtype=float)
    coeff = np.asarray(coeff)

    if occ.ndim != 1:
        raise ValueError('occ must be a 1-D array.')
    if coeff.ndim != 2:
        raise ValueError('coeff must be a 2-D array.')
    if coeff.shape[1] != occ.size:
        raise ValueError('The number of columns in coeff must match the size of occ.')
    if coeff.shape[1] > coeff.shape[0]:
        raise ValueError('nctr cannot be larger than nprim.')
    if not np.isfinite(tol) or tol < 0.:
        raise ValueError('tol must be finite and nonnegative.')
    if np.any(~np.isfinite(occ)) or np.any(~np.isfinite(coeff)):
        raise ValueError('occ and coeff must contain only finite values.')

    order = np.argsort(-occ, kind='stable')
    occ = occ[order].copy()
    coeff = coeff[:,order].copy()

    degenerate = occ[:-1] - occ[1:] < tol
    block_start = 0
    for block_end in np.where(~degenerate)[0] + 1:
        if block_end - block_start > 1:
            idx = np.argsort(np.abs(coeff[-1,block_start:block_end]), kind='stable')
            occ[block_start:block_end] = occ[block_start:block_end][idx]
            coeff[:,block_start:block_end] = coeff[:,block_start:block_end][:,idx]
        block_start = block_end

    if occ.size - block_start > 1:
        idx = np.argsort(np.abs(coeff[-1,block_start:]), kind='stable')
        occ[block_start:] = occ[block_start:][idx]
        coeff[:,block_start:] = coeff[:,block_start:][:,idx]

    return occ, coeff


if __name__ == '__main__':
    from pyscf import gto, scf, cc
    from pygto.lib import pyscf_helper
    atm = 'C'
    spin = 2
    config = [
        (2,2,0,0), (2,0,0,0)
    ]
    frozen = 1
    fbas = 'cc-pvdz'
    val_l = [0,1]

    basis = pyscf_helper.load_basis(fbas, atm, keep_l=val_l)
    cgto = ContractedBasis.init_from_pyscf_basis(basis, atm=atm)
    spec = BasisSpec.init_from_pyscf_basis(basis, atm=atm)
    ano_input_func = pyscf_helper.get_ano_input_func(
        atm, scf.ROHF, mol_settings={'spin':spin}, config=config,
        CORR=cc.CCSD, corr_settings={'frozen':frozen}
    )

    ano = ANO(spec, ano_input_func, atm)
    ano.pct_occ = 0.99
    ano.nfree_by_l = {0:1, 1:1}
    ano.kernel()

    ano.log_note('Reference basis:')
    cgto.dump_basis()
    ano.log_note('')
    ano.log_note('Final CCSD ANO basis with decontraction:')
    ano.basis.dump_basis()
    ano.log_note('')
    ano.log_note('Fully contracted CCSD ANO basis')
    ano.ctr_basis.dump_basis()
