''' This example demonstrates how to use the ChannelReduction workflow to generate a
    series of basis sets with progressively smaller angular-momentum channels.

    Starting from the nearly complete 5s6p ccECP valence basis for carbon generated by
    the TCAO example ("02_tcao.py"), the workflow reduces one channel at a time while
    holding the other fixed. It reoptimizes the retained exponents after each reduction
    and stops reducing a channel after the energy increase exceeds `ftol` (0.01 Ha here).

    NOTE: This example relies on PySCF for ROHF calculations.
'''

from pathlib import Path

from pygto import lib
from pygto.basis import BasisSpec
from pygto.workflow import ChannelReduction
from pygto.data.elements import get_spin

from pyscf import scf


DATA_DIR = Path(__file__).resolve().parent / 'data'


if __name__ == '__main__':
    atm = 'C'
    spin = get_spin(atm)
    basis = str(DATA_DIR / 'c_ccecp_val.dat')  # Generated by `02_tcao.py`.
    val_l = [0, 1]
    ecp = 'ccecp'
    ftol = 1e-2  # Energy-error tolerance for stopping channel reduction.

    ''' Construct the ROHF total-energy cost function for carbon with the ccECP.
    '''
    cost_func = lib.pyscf_helper.get_cost_func(
        atm, scf.ROHF, mol_settings={'spin':spin, 'ecp':ecp}, keep_l=val_l,
    )

    ''' Load the TCAO basis set from a file.
    '''
    spec = BasisSpec.init_from_basis(basis, atm,
        keep_l=val_l,   # Retain only the s and p channels.
    )

    ''' Perform channel reduction.
    '''
    opt = ChannelReduction(spec, cost_func, ftol=ftol).set(verbose=5)
    opt.kernel()

    ''' Reference results:

        `ChannelReduction.kernel` creates a `summary` directory containing results
        for all channels.

        The results for the s-channel, as in `summary/channel_0/summary.csv`, are

            structure,cost,delta_f
            5s,-5.3142247149,0.000e+00
            4s,-5.3138699558,3.548e-04
            3s,-5.3121443880,2.080e-03
            2s,-5.2802375427,3.399e-02

        The results for the p-channel, as in `summary/channel_1/summary.csv`, are

            structure,cost,delta_f
            6p,-5.3142247149,0.000e+00
            5p,-5.3140495925,1.751e-04
            4p,-5.3125708043,1.654e-03
            3p,-5.3015210509,1.270e-02
    '''
